name: pytorch
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - backcall
  - backports
  - backports.functools_lru_cache
  - blas
  - bleach
  - bottleneck
  - brotli
  - brotli-bin
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cloudpickle
  - colorama
  - cudatoolkit
  - cycler
  - cytoolz
  - dask-core
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - ffmpeg
  - fontconfig
  - fonttools
  - freeglut
  - freetype
  - fsspec
  - geos
  - gettext
  - giflib
  - glib
  - glib-tools
  - graphite2
  - gst-plugins-base
  - gstreamer
  - h5py
  - harfbuzz
  - hdf5
  - icu
  - imagecodecs-lite
  - imageio
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jasper
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libdeflate
  - libffi
  - libglib
  - libiconv
  - liblapack
  - libopencv
  - libpng
  - libprotobuf
  - libsodium
  - libtiff
  - libuv
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - locket
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nbconvert
  - nbformat
  - networkx
  - ninja
  - ninja-base
  - notebook
  - numexpr
  - numpy
  - numpy-base
  - opencv
  - openh264
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - partd
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - prometheus_client
  - prompt-toolkit
  - protobuf
  - pthread-stubs
  - ptyprocess
  - py-opencv
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - pywavelets
  - pywget
  - pyyaml
  - pyzmq
  - qt
  - scikit-image
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - shapely
  - sip
  - six
  - sqlite
  - tensorboardx
  - terminado
  - testpath
  - threadpoolctl
  - tifffile
  - tk
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - unicodedata2
  - wcwidth
  - webencodings
  - wheel
  - x264
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip:
      - charset-normalizer
      - filelock
      - huggingface-hub
      - idna
      - importlib-metadata
      - regex
      - requests
      - tokenizers
      - transformers
      - urllib3
      - zipp
